from .test_birth_reg import *
from .test_bug_reports import *
from .test_death_reg import *
from .test_help import *
from .test_join import *
from .test_lookups import *
from .test_models import *
from .test_postpartum import *
from .test_pregnancy import *
from .test_refer import *
from .test_told import *
from .test_utils import *
from .test_views import *
